-- Storage for image variants generated by the imagine executor.
-- Each row is one Gemini-generated rendering of one slot prompt.
-- The picker (npm run pick) sets `picked = true` on the chosen variant
-- per slot, and the publisher reads picked rows to build asset_paths.

create table magazine_image_variants (
  id bigserial primary key,
  run_id uuid not null,
  slot text not null,
  -- slot ∈ cover-start, cover-end, trend-1, trend-2, trend-3, curator-1, curator-2
  variant_index integer not null check (variant_index >= 0),
  storage_path text not null,
  -- path inside the magazine-assets bucket
  prompt text not null,
  alt_text text,
  picked boolean not null default false,
  generation_model text not null default 'gemini-2.5-flash-image-preview',
  estimated_cost_usd numeric(10, 6) not null default 0.039,
  generated_at timestamptz not null default now(),
  picked_at timestamptz,
  unique (run_id, slot, variant_index)
);

create index magazine_image_variants_run_id_idx on magazine_image_variants (run_id);
create index magazine_image_variants_picked_idx on magazine_image_variants (run_id, picked) where picked = true;

alter table magazine_image_variants enable row level security;
revoke select on magazine_image_variants from anon, authenticated;

comment on table magazine_image_variants is 'the-edit: image variants per run/slot. Service role only.';

-- Storage bucket — variants land at magazine-assets/{runId}/{slot}/{variantIdx}.png
insert into storage.buckets (id, name, public)
values ('magazine-assets', 'magazine-assets', false)
on conflict (id) do nothing;
